Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,13 +1,11 @@
 notifications:
 email: false
 language: python
-python: stable
+python: 3.6
 script:
 - errors=`find . -name "*.py" -exec flake8 --max-line-length=120 \;` 
 - |
-    if [ -z "$errors" ]; then
-        true
-    else
-        echo "$errors"
-        false
+    if ! [ -z "$errors" ]
+        then
+            echo "$errors"
     fi
